# Form implementation generated from reading ui file 'Main.app.home.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(677, 617)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    \n"
"    background-color: rgb(0, 2, 12);\n"
"}")
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    \n"
"    background-color: rgb(0, 2, 12);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.slide_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.slide_widget.setMinimumSize(QtCore.QSize(120, 0))
        self.slide_widget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.slide_widget.setStyleSheet("background-color: rgb(0, 1, 3);\n"
"border-radius: 10px;\n"
"background-color: rgb(15, 16, 36);")
        self.slide_widget.setObjectName("slide_widget")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.slide_widget)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.toolBox = QtWidgets.QToolBox(parent=self.slide_widget)
        self.toolBox.setStyleSheet("QToolBox::tab{\n"
"    \n"
"    background-color: qlineargradient(spread:repeat, x1:0, y1:1, x2:1, y2:1, stop:0 rgba(220, 20, 60, 255), stop:0.9375 rgba(100, 9, 27, 255));\n"
"    border-radius: 5px;\n"
"}")
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 200, 428))
        self.page.setObjectName("page")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.widget_11 = QtWidgets.QWidget(parent=self.page)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label = QtWidgets.QLabel(parent=self.widget_11)
        font = QtGui.QFont()
        font.setFamily("Morabba Medium")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.verticalLayout_15.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(parent=self.widget_11)
        font = QtGui.QFont()
        font.setFamily("Morabba Medium")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_15.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(parent=self.widget_11)
        font = QtGui.QFont()
        font.setFamily("Morabba Medium")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_15.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_15.addItem(spacerItem)
        self.verticalLayout_16.addWidget(self.widget_11)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 200, 428))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(parent=self.page_2)
        self.commandLinkButton.setStyleSheet("background-color: rgb(220, 20, 60);")
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.verticalLayout_17.addWidget(self.commandLinkButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_17.addItem(spacerItem1)
        self.toolBox.addItem(self.page_2, "")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.toolBox.addItem(self.page_6, "")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.toolBox.addItem(self.page_7, "")
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.toolBox.addItem(self.page_8, "")
        self.verticalLayout_14.addWidget(self.toolBox)
        self.horizontalLayout.addWidget(self.slide_widget)
        self.main = QtWidgets.QWidget(parent=self.centralwidget)
        self.main.setMinimumSize(QtCore.QSize(400, 0))
        self.main.setObjectName("main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.w1 = QtWidgets.QWidget(parent=self.main)
        self.w1.setObjectName("w1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.w1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.profile = QtWidgets.QWidget(parent=self.w1)
        self.profile.setObjectName("profile")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.profile)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.head_main = QtWidgets.QWidget(parent=self.profile)
        self.head_main.setMinimumSize(QtCore.QSize(0, 200))
        self.head_main.setStyleSheet("background-color: rgb(15, 16, 36);\n"
"border-radius:5px;")
        self.head_main.setObjectName("head_main")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.head_main)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 5)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_3 = QtWidgets.QWidget(parent=self.head_main)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 170))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_5 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_5.setObjectName("widget_5")
        self.slide_open_btn = QtWidgets.QPushButton(parent=self.widget_5)
        self.slide_open_btn.setGeometry(QtCore.QRect(0, 0, 30, 30))
        self.slide_open_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.slide_open_btn.setMaximumSize(QtCore.QSize(30, 30))
        self.slide_open_btn.setStyleSheet("background-color:rgb(220, 20, 60);\n"
"border-radius:5px;")
        self.slide_open_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logos/hamburger-menu.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.slide_open_btn.setIcon(icon)
        self.slide_open_btn.setIconSize(QtCore.QSize(20, 20))
        self.slide_open_btn.setObjectName("slide_open_btn")
        # self.slide_open_btn.clicked.connect(self.slide_size)




















        self.horizontalLayout_6.addWidget(self.widget_5)
        self.widget_4 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.profile_btn = QtWidgets.QPushButton(parent=self.widget_4)
        self.profile_btn.setMinimumSize(QtCore.QSize(110, 110))
        self.profile_btn.setMaximumSize(QtCore.QSize(110, 110))
        self.profile_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.profile_btn.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(220, 20, 60, 255), stop:0.9375 rgba(100, 9, 27, 255));\n"
"    \n"
"    border-radius: 55px;\n"
"}")
        self.profile_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("logos/noun-member-983463.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.profile_btn.setIcon(icon1)
        self.profile_btn.setIconSize(QtCore.QSize(60, 60))
        self.profile_btn.setObjectName("profile_btn")
        self.horizontalLayout_8.addWidget(self.profile_btn)
        self.horizontalLayout_6.addWidget(self.widget_4)
        self.widget_2 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6.addWidget(self.widget_2)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.user_name_label = QtWidgets.QLabel(parent=self.head_main)
        font = QtGui.QFont()
        font.setFamily("Morabba Black")
        font.setPointSize(16)
        font.setBold(True)
        self.user_name_label.setFont(font)
        self.user_name_label.setWhatsThis("")
        self.user_name_label.setStyleSheet("color: rgb(220, 20, 60);")
        self.user_name_label.setObjectName("user_name_label")
        self.verticalLayout_3.addWidget(self.user_name_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.search_wid = QtWidgets.QWidget(parent=self.head_main)
        self.search_wid.setMinimumSize(QtCore.QSize(0, 40))
        self.search_wid.setStyleSheet("")
        self.search_wid.setObjectName("search_wid")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.search_wid)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.search_wid)
        self.lineEdit.setMinimumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setFamily("Morabba Medium")
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(206, 208, 239);\n"
"border-color: rgb(220, 20, 60);\n"
"border-radius:5px;")
        self.lineEdit.setText("")
        self.lineEdit.setFrame(False)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_13.addWidget(self.lineEdit)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem3)
        self.verticalLayout_3.addWidget(self.search_wid)
        self.horizontalLayout_5.addWidget(self.head_main)
        self.verticalLayout_4.addWidget(self.profile)
        self.mead_main = QtWidgets.QWidget(parent=self.w1)
        self.mead_main.setMinimumSize(QtCore.QSize(250, 0))
        self.mead_main.setObjectName("mead_main")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.mead_main)
        self.horizontalLayout_3.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.setting_btn = QtWidgets.QPushButton(parent=self.mead_main)
        self.setting_btn.setMinimumSize(QtCore.QSize(80, 80))
        self.setting_btn.setMaximumSize(QtCore.QSize(80, 80))
        self.setting_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.setting_btn.setMouseTracking(True)
        self.setting_btn.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(220, 20, 60);\n"
"    border-radius:10px;\n"
"    \n"
"    \n"
"\n"
"}")
        self.setting_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("logos/noun-setting-6518124.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.setting_btn.setIcon(icon2)
        self.setting_btn.setIconSize(QtCore.QSize(50, 50))
        self.setting_btn.setCheckable(True)
        self.setting_btn.setChecked(False)
        self.setting_btn.setAutoRepeat(False)
        self.setting_btn.setObjectName("setting_btn")
        self.horizontalLayout_3.addWidget(self.setting_btn)
        self.pin_btn = QtWidgets.QPushButton(parent=self.mead_main)
        self.pin_btn.setMinimumSize(QtCore.QSize(80, 80))
        self.pin_btn.setMaximumSize(QtCore.QSize(80, 80))
        self.pin_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pin_btn.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(220, 20, 60);\n"
"    border-radius:10px;\n"
"\n"
"\n"
"\n"
"}")
        self.pin_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("logos/noun-pin-6524456.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pin_btn.setIcon(icon3)
        self.pin_btn.setIconSize(QtCore.QSize(50, 50))
        self.pin_btn.setObjectName("pin_btn")
        self.horizontalLayout_3.addWidget(self.pin_btn)
        self.history_btn = QtWidgets.QPushButton(parent=self.mead_main)
        self.history_btn.setMinimumSize(QtCore.QSize(80, 80))
        self.history_btn.setMaximumSize(QtCore.QSize(80, 80))
        self.history_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.history_btn.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(220, 20, 60);\n"
"    border-radius:10px;\n"
"\n"
"\n"
"\n"
"}")
        self.history_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("logos/noun-history-1559603.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.history_btn.setIcon(icon4)
        self.history_btn.setIconSize(QtCore.QSize(50, 50))
        self.history_btn.setObjectName("history_btn")
        self.horizontalLayout_3.addWidget(self.history_btn)
        self.verticalLayout_4.addWidget(self.mead_main)
        self.verticalLayout.addWidget(self.w1)
        self.w2 = QtWidgets.QWidget(parent=self.main)
        self.w2.setObjectName("w2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.w2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_line_1 = QtWidgets.QWidget(parent=self.w2)
        self.button_line_1.setObjectName("button_line_1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.button_line_1)
        self.verticalLayout_5.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.bakhsh_haye_main_toolbox = QtWidgets.QToolBox(parent=self.button_line_1)
        font = QtGui.QFont()
        font.setFamily("Morabba")
        font.setPointSize(10)
        font.setBold(True)
        self.bakhsh_haye_main_toolbox.setFont(font)
        self.bakhsh_haye_main_toolbox.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.bakhsh_haye_main_toolbox.setAcceptDrops(False)
        self.bakhsh_haye_main_toolbox.setStyleSheet("QToolBox::tab{\n"
"    \n"
"    background-color: qlineargradient(spread:repeat, x1:0, y1:1, x2:1, y2:1, stop:0 rgba(220, 20, 60, 255), stop:0.9375 rgba(100, 9, 27, 255));\n"
"    border-radius: 5px;\n"
"}")
        self.bakhsh_haye_main_toolbox.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.bakhsh_haye_main_toolbox.setLineWidth(1)
        self.bakhsh_haye_main_toolbox.setObjectName("bakhsh_haye_main_toolbox")
        self.widget = QtWidgets.QWidget()
        self.widget.setGeometry(QtCore.QRect(0, -51, 436, 158))
        self.widget.setObjectName("widget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_6 = QtWidgets.QWidget(parent=self.widget)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widget_8 = QtWidgets.QWidget(parent=self.widget_6)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_16.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.widget_8)
        self.pushButton_12.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Morabba Medium")
        font.setPointSize(10)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(220, 20, 60);\n"
"    border-radius:5px;\n"
"    \n"
"    \n"
"\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_16.addWidget(self.pushButton_12)
        self.pushButton_14 = QtWidgets.QPushButton(parent=self.widget_8)
        self.pushButton_14.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Morabba Medium")
        font.setPointSize(10)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(220, 20, 60);\n"
"    border-radius:5px;\n"
"    \n"
"    \n"
"\n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_16.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(parent=self.widget_8)
        self.pushButton_15.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Morabba Medium")
        font.setPointSize(10)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(220, 20, 60);\n"
"    border-radius:5px;\n"
"    \n"
"    \n"
"\n"
"}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_16.addWidget(self.pushButton_15)
        self.verticalLayout_11.addWidget(self.widget_8)
        self.widget_7 = QtWidgets.QWidget(parent=self.widget_6)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_15.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.widget_7)
        self.pushButton_13.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Morabba Medium")
        font.setPointSize(10)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(220, 20, 60);\n"
"    border-radius:5px;\n"
"    \n"
"    \n"
"\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_15.addWidget(self.pushButton_13)
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.widget_7)
        self.pushButton_10.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Morabba Medium")
        font.setPointSize(10)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(220, 20, 60);\n"
"    border-radius:5px;\n"
"    \n"
"    \n"
"\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_15.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.widget_7)
        self.pushButton_11.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Morabba Medium")
        font.setPointSize(10)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(220, 20, 60);\n"
"    border-radius:5px;\n"
"    \n"
"    \n"
"\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_15.addWidget(self.pushButton_11)
        self.verticalLayout_11.addWidget(self.widget_7)
        self.verticalLayout_10.addWidget(self.widget_6)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("logos/noun-calculator-1465099.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bakhsh_haye_main_toolbox.addItem(self.widget, icon5, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 453, 107))
        self.page_4.setObjectName("page_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_9 = QtWidgets.QWidget(parent=self.page_4)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.widget_10 = QtWidgets.QWidget(parent=self.widget_9)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_14.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pushButton_17 = QtWidgets.QPushButton(parent=self.widget_10)
        self.pushButton_17.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Morabba Medium")
        font.setPointSize(10)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(220, 20, 60);\n"
"    border-radius:5px;\n"
"    \n"
"    \n"
"\n"
"}")
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_14.addWidget(self.pushButton_17)
        self.pushButton_16 = QtWidgets.QPushButton(parent=self.widget_10)
        self.pushButton_16.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Morabba Medium")
        font.setPointSize(10)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(220, 20, 60);\n"
"    border-radius:5px;\n"
"    \n"
"    \n"
"\n"
"}")
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_14.addWidget(self.pushButton_16)
        self.pushButton_18 = QtWidgets.QPushButton(parent=self.widget_10)
        self.pushButton_18.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Morabba Medium")
        font.setPointSize(10)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(220, 20, 60);\n"
"    border-radius:5px;\n"
"    \n"
"    \n"
"\n"
"}")
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_14.addWidget(self.pushButton_18)
        self.verticalLayout_13.addWidget(self.widget_10)
        self.verticalLayout_12.addWidget(self.widget_9)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("logos/noun-education-3519198.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bakhsh_haye_main_toolbox.addItem(self.page_4, icon6, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget1 = QtWidgets.QWidget(parent=self.page_5)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, 9, -1, 9)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.widget1)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Morabba Medium")
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(220, 20, 60);\n"
"border-radius:5px;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_12.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget1)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Morabba Medium")
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(220, 20, 60);\n"
"border-radius:5px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_12.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(parent=self.widget1)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton.setStyleSheet("background-color: rgb(220, 20, 60);\n"
"border-radius:5px;")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_12.addWidget(self.pushButton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 9, 0, 9)
        self.horizontalLayout_10.setSpacing(9)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.widget1)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Morabba Medium")
        font.setPointSize(10)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: rgb(220, 20, 60);\n"
"border-radius:5px;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_10.addWidget(self.pushButton_6)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.widget1)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Morabba Medium")
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(220, 20, 60);\n"
"border-radius:5px;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_10.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.widget1)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Morabba Medium")
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(220, 20, 60);\n"
"border-radius:5px;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_10.addWidget(self.pushButton_4)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, 9, -1, 9)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.widget1)
        self.pushButton_9.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Morabba Medium")
        font.setPointSize(10)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color: rgb(220, 20, 60);\n"
"border-radius:5px;")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_11.addWidget(self.pushButton_9)
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.widget1)
        self.pushButton_8.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Morabba Medium")
        font.setPointSize(10)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-color: rgb(220, 20, 60);\n"
"border-radius:5px;")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_11.addWidget(self.pushButton_8)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.widget1)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Morabba Medium")
        font.setPointSize(10)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color: rgb(220, 20, 60);\n"
"border-radius:5px;")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_11.addWidget(self.pushButton_7)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.verticalLayout_2.addWidget(self.widget1)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("logos/noun-equal-2492172.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bakhsh_haye_main_toolbox.addItem(self.page_5, icon7, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.bakhsh_haye_main_toolbox.addItem(self.page_3, "")
        self.verticalLayout_5.addWidget(self.bakhsh_haye_main_toolbox)
        self.horizontalLayout_2.addWidget(self.button_line_1)
        self.verticalLayout.addWidget(self.w2)
        self.horizontalLayout.addWidget(self.main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(1)
        self.bakhsh_haye_main_toolbox.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "تماس با ما :"))
        self.label_3.setText(_translate("MainWindow", "09917359800"))
        self.label_2.setText(_translate("MainWindow", "09124945046"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "ارتباط با ما"))
        self.commandLinkButton.setText(_translate("MainWindow", "دانلود فایل راهنما"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "راهنما"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _translate("MainWindow", "تنظیمات"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_7), _translate("MainWindow", "سوالات متداول"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_8), _translate("MainWindow", "خروج از برنامه"))
        self.user_name_label.setText(_translate("MainWindow", "نام کاربری"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "جست و جو ..."))
        self.pushButton_12.setText(_translate("MainWindow", "عبارات جبری"))
        self.pushButton_14.setText(_translate("MainWindow", "کسر ها"))
        self.pushButton_15.setText(_translate("MainWindow", "الگو ها"))
        self.pushButton_13.setText(_translate("MainWindow", "آمار و احتمال"))
        self.pushButton_10.setText(_translate("MainWindow", "نمودار ها"))
        self.pushButton_11.setText(_translate("MainWindow", "ماشین حساب"))
        self.bakhsh_haye_main_toolbox.setItemText(self.bakhsh_haye_main_toolbox.indexOf(self.widget), _translate("MainWindow", "ریاضیات"))
        self.pushButton_17.setText(_translate("MainWindow", "مثلثات"))
        self.pushButton_16.setText(_translate("MainWindow", "دایره"))
        self.pushButton_18.setText(_translate("MainWindow", "چند ضلعی ها"))
        self.bakhsh_haye_main_toolbox.setItemText(self.bakhsh_haye_main_toolbox.indexOf(self.page_4), _translate("MainWindow", "هندسه"))
        self.pushButton_3.setText(_translate("MainWindow", " فصل 3"))
        self.pushButton_2.setText(_translate("MainWindow", "فصل 2"))
        self.pushButton.setText(_translate("MainWindow", "فصل 1"))
        self.pushButton_6.setText(_translate("MainWindow", "فصل 6"))
        self.pushButton_5.setText(_translate("MainWindow", "فصل 5"))
        self.pushButton_4.setText(_translate("MainWindow", "فصل 4"))
        self.pushButton_9.setText(_translate("MainWindow", "فصل 9"))
        self.pushButton_8.setText(_translate("MainWindow", "فصل 8"))
        self.pushButton_7.setText(_translate("MainWindow", "فصل 7"))
        self.bakhsh_haye_main_toolbox.setItemText(self.bakhsh_haye_main_toolbox.indexOf(self.page_5), _translate("MainWindow", "کتاب ریاضی هشتم"))
        self.bakhsh_haye_main_toolbox.setItemText(self.bakhsh_haye_main_toolbox.indexOf(self.page_3), _translate("MainWindow", "تمامی قابلیت ها"))

    # def slide_size (self):
    #     if self.slide_widget.width()==0 :
    #         self.slide_widget.width(200)
    #     else :
    #         self.slide_widget.width(0)

    #     else:
    #         newWidth = 0
    #
    #     self.animation = QtCore.QPropertyAnimation(self.slide_widget,b"maximumWidth")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
